### ISSUE TITLE
WMS-01 (motion sensor) - Device is found but no controls avalible

### ISSUE THREAD

**Issue by bm500** [thomasloven/hass-plejd#54] opened 2024-02-07 17:55 UTC
After installing WMS-01 the integration founds the device but there is no controls avalible.
Pls see picture as well as diagnistic file in link.
If I can help, I will be happy to do so.

![Screenshot_20240207-190554_2](https://github.com/thomasloven/hass_plejd/assets/71224205/066c3f25-aa35-4456-9690-c6080fd0e942)

![WMS-01](https://github.com/thomasloven/hass_plejd/assets/71224205/1cdd9ee7-9534-4dbb-85f2-1c69eacd9b35)
[config_entry-plejd-aac7e4b63e67aaf4c4a30625da5a5458.json (5).txt](https://github.com/thomasloven/hass_plejd/files/14199706/config_entry-plejd-aac7e4b63e67aaf4c4a30625da5a5458.json.5.txt)

**Comment by anordnes** [comment] 2024-02-16 23:01
Also tried this . Same result with no sensor. The sensor is really nice looking so hope it will work

**Comment by thomasloven** [comment] 2024-02-17 09:56
I've got one on it's way in the mail, so I'm sure this will be fixed...

**Comment by anordnes** [comment] 2024-02-17 09:58
Ok. Nice!

If i can help in some way i would be happy to do so. Just let me know.

Aleksander
Norway

lør. 17. feb. 2024 kl. 10:56 skrev Thomas Lovén ***@***.***>:

**Comment by thomasloven** [comment] 2024-02-20 22:10
There we go!

**Comment by anordnes** [comment] 2024-02-21 15:18
I have tried to update the integration and now i see the sensor with entity put i doesnt not reconize movement

**Comment by bm500** [comment] 2024-02-21 15:32
I have also tested the new version and the sensor seams to work ok. Movement is recognized as soon as I enter the room.

**Comment by thomasloven** [comment] 2024-02-21 15:41
> I have tried to update the integration and now i see the sensor with entity put i doesnt not reconize movement

Wait... you're the one who emailed me and had only a WMS-01 and nothing else, right?
So you don't know if your hass machine can connect to your Plejd mesh at all...
To answer your email, no a Shelly proxy will not work - as stated in the readme.

Did Plejd pop up for you as autodetected, or did you add it manually?

**Comment by anordnes** [comment] 2024-02-21 15:45
Yes. I emailed you. I have only this plejd sensor. It did autodetected but
when i updated the plugin it was not so i added it manuelt


ons. 21. feb. 2024 kl. 16:41 skrev Thomas Lovén ***@***.***>:

**Comment by anordnes** [comment] 2024-02-21 17:07
Tried to delete the integration and restartet and then it was autodiscovered but it still does  not show movement

**Comment by anordnes** [comment] 2024-02-21 19:39
I have tried with the logger pyplejd.dev and pyplejd.ble  put nothings comes up in the log. I use the normal log on the left side of HA. Or is there another log i should check?

Also tried with the built in bluetooth in rpi4 and with esphome bluetooth proxy. but nothing. The sensor says available and ready

**Comment by anordnes** [comment] 2024-02-22 08:29
I tried alot last night and this morning. But it doesnot react on movement.  In the plejd app on the iphone it does show movement. i downloaded the diagnostic file if it can be to any use.

[config_entry-plejd-3530f27ba6b2a2b2e5c30be4220e5c97.json](https://github.com/thomasloven/hass-plejd/files/14370991/config_entry-plejd-3530f27ba6b2a2b2e5c30be4220e5c97.json)

I tried the plejd addon ([hassio-plejd) and i get some date there when i walk past the sensor. https://github.com/icanos/hassio-plejd/issues/300

**Comment by anordnes** [comment] 2024-02-24 17:11
Seems like it wont connect to the mesh. Could it be that i only have one Plejd device?

2024-02-24 12:26:58.540 DEBUG (MainThread) [pyplejd.ble] Saw device F0:3B:87:13:8B:39: F0-3B-87-13-8B-39 (rssi: -71, prev: -1000000.0)
2024-02-24 12:26:58.541 DEBUG (MainThread) [pyplejd.ble] Trying to connect to mesh
2024-02-24 12:26:58.541 DEBUG (MainThread) [pyplejd.ble] Failed to connect to plejd mesh - No valid devices: {BLEDevice(F0:3B:87:13:8B:39, P mesh): -40, BLEDevice(F0:3B:87:13:8B:39, F0-3B-87-13-8B-39): -71} (set())
2024-02-24 12:26:58.541 DEBUG (MainThread) [custom_components.plejd.plejd_site] Ping failed
2024-02-24 12:27:34.649 DEBUG (MainThread) [pyplejd.ble] Saw device F0:3B:87:13:8B:39: P mesh (rssi: -63, prev: -1000000.0)
2024-02-24 12:27:34.649 DEBUG (MainThread) [pyplejd.ble] Trying to connect to mesh
2024-02-24 12:27:34.649 DEBUG (MainThread) [pyplejd.ble] Failed to connect to plejd mesh - No valid devices: {BLEDevice(F0:3B:87:13:8B:39, P mesh): -40, BLEDevice(F0:3B:87:13:8B:39, F0-3B-87-13-8B-39): -71, BLEDevice(F0:3B:87:13:8B:39, P mesh): -63} (set())

**Comment by thomasloven** [comment] 2024-02-25 20:10
Oh! I see what the issue is now.

Since battery powered devices go to sleep when they are not used, they cannot be reliably used for the mesh connection. Therefore they are ignored when the initial connection is made.

I'll have to think a bit about how to handle this one...

**Closed by thomasloven** 2024-02-25 20:10 UTC

**Comment by anordnes** [comment] 2024-02-25 20:41
Excellent. Thanks. If there is something i could do in the config or something to "hack" around the issuse it would be great. I guess most people have several plejd devices but i only choose this one because of its smart design.
